"""initial schema"""

import sqlalchemy as sa

from alembic import op

revision = "8c1724b013ba"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("encrypted_google_refresh_token", sa.Text(), nullable=True),
        sa.Column("timezone", sa.String(), nullable=False),
        sa.Column("morning_run_time", sa.String(), nullable=False),
        sa.Column("evening_report_time", sa.String(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("automatic_sending_enabled", sa.Boolean(), nullable=False),
        sa.Column("session_version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "followup_threads",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("gmail_thread_id", sa.String(length=128), nullable=False),
        sa.Column("original_message_id", sa.String(length=128), nullable=False),
        sa.Column("recipient_email", sa.String(length=320), nullable=False),
        sa.Column("recipient_name", sa.String(), nullable=False),
        sa.Column("company_or_domain", sa.String(), nullable=False),
        sa.Column("subject", sa.Text(), nullable=False),
        sa.Column("preview", sa.String(length=500), nullable=False),
        sa.Column("original_sent_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("classification", sa.String(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("followup1_sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("followup2_sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_reason", sa.Text(), nullable=True),
        sa.Column("pending_number", sa.Integer(), nullable=True),
        sa.Column("pending_message_id", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "gmail_thread_id"),
    )
    op.create_index(
        op.f("ix_followup_threads_original_sent_at"),
        "followup_threads",
        ["original_sent_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_followup_threads_status"), "followup_threads", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_followup_threads_user_id"), "followup_threads", ["user_id"], unique=False
    )
    op.create_index("ix_user_status", "followup_threads", ["user_id", "status"], unique=False)
    op.create_table(
        "scheduler_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("job_type", sa.String(length=32), nullable=False),
        sa.Column("local_date", sa.Date(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("report", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "job_type", "local_date"),
    )
    op.create_table(
        "activity_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("followup_thread_id", sa.Integer(), nullable=True),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["followup_thread_id"],
            ["followup_threads.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_activity_logs_created_at"), "activity_logs", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_activity_logs_user_id"), "activity_logs", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_activity_logs_user_id"), table_name="activity_logs")
    op.drop_index(op.f("ix_activity_logs_created_at"), table_name="activity_logs")
    op.drop_table("activity_logs")
    op.drop_table("scheduler_runs")
    op.drop_index("ix_user_status", table_name="followup_threads")
    op.drop_index(op.f("ix_followup_threads_user_id"), table_name="followup_threads")
    op.drop_index(op.f("ix_followup_threads_status"), table_name="followup_threads")
    op.drop_index(op.f("ix_followup_threads_original_sent_at"), table_name="followup_threads")
    op.drop_table("followup_threads")
    op.drop_table("users")
    # ### end Alembic commands ###
